# Generated by Django 2.1.7 on 2019-08-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('upwd', models.CharField(max_length=40)),
                ('uemail', models.CharField(max_length=30)),
                ('uAddressee', models.CharField(max_length=40)),
                ('uReceivingAddress', models.CharField(max_length=40)),
                ('uPostalCode', models.CharField(max_length=6)),
            ],
        ),
    ]
