# Generated by Django 2.1.7 on 2019-08-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='uphone',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
