# Generated by Django 2.1.7 on 2019-04-22 09:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_auto_20190419_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hcontent',
            field=tinymce.models.HTMLField(),
        ),
    ]
